# Rochester Law CMS - Development Docker Compose Override
# Use this file for development with hot reload and development tools
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

version: '3.8'

services:
  # Override app service for development
  app:
    build:
      target: development
    container_name: rochester-law-app-dev
    environment:
      NODE_ENV: development
      NEXTAUTH_SECRET: development-secret-key-change-in-production
      NEXT_PUBLIC_DEMO_MODE: true
      DEBUG_MODE: true
      SEED_DEMO_DATA: true
    volumes:
      # Bind mount source code for hot reload
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
      - "9229:9229"  # Node.js debugger port
    command: ["npm", "run", "dev"]

  # Development database with less strict settings
  database:
    environment:
      POSTGRES_DB: rochester_law_cms_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: rochester-law-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@rochester-law.dev
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    depends_on:
      - database
    networks:
      - rochester-law-network
    profiles:
      - development

  # Optional: Redis Commander for cache management
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: rochester-law-redis-commander
    environment:
      REDIS_HOSTS: redis:redis:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD:-cache_password}
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - rochester-law-network
    profiles:
      - development

  # Disable nginx in development
  nginx:
    profiles:
      - production